### ISSUE TITLE
EmbeddingModule   compute_embedding()

### ISSUE THREAD

**Issue by DSJYTECHNOLOGY** [lxd99/CTCP#1]
代码EmbeddingModule   中的compute_embedding()未实现，一直显示Nonetype

**Comment by lxd99** [comment]
你好，EmbeddingModule是一个基类，只是定义了compute_embedding()的接口，具体的计算逻辑是由子类实现的（IdentityEmbedding，AggregateEmbedding）。想要选择不同的embedding类型，可以通过改变main.py里面的超参数embedding_module实现 。
