### ISSUE TITLE
How to use the GPU while the Cudaversion of dgl needs to satisfy python>=3.8?

### ISSUE THREAD

**Issue by jinjiao97** [lxd99/CTCP#4]
How to use the GPU while the Cuda version of dgl needs to satisfy python>=3.8?
https://www.dgl.ai/pages/start.html

**Comment by lxd99** [comment]
Hi, what is the dgl version of your environment? You can try to run the code with the package version specified in the Readme, where GPU can be normally used on my server.

The package versions are
- python == 3.7.0
- pytorch == 1.9.1
- dgl == 0.8.2
- scikit-learn == 1.0
- numpy == 1.21.5
- pandas == 1.1.5
- tqdm == 4.62.3

**Comment by jinjiao97** [comment]
Thanks for your help!
I will try again!
